version: '3'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: app

    mutable_state:
        image: microservices-for-everyone/persistence_base
        build: docker/base/
        volumes:
            - ./:/opt
        command: php src/MutableState/run.php
        depends_on:
            - mysql

    redis:
        image: redis:3.2

    sequence_server:
        image: microservices-for-everyone/persistence_base
        volumes:
            - ./:/opt
        command: php -S 0.0.0.0:80 -t src/Sequence/server/
        depends_on:
            - redis

    sequence_client:
        image: microservices-for-everyone/persistence_base
        volumes:
            - ./:/opt
        command: php src/Sequence/client.php
        depends_on:
            - sequence_server

    event_sourcing:
        image: microservices-for-everyone/persistence_base
        volumes:
            - ./:/opt
        command: php src/EventSourcing/run.php

    cassandra:
        image: cassandra

    cassandra2:
        image: cassandra
        depends_on:
            - cassandra
        environment:
            CASSANDRA_SEEDS: cassandra

    cassandra3:
        image: cassandra
        depends_on:
            - cassandra
        environment:
            CASSANDRA_SEEDS: cassandra

    cqlsh:
        image: cassandra
        command: cqlsh cassandra
        depends_on:
            - cassandra

    distributed_storage:
        image: microservices-for-everyone/persistence_base
        volumes:
            - ./:/opt
        command: php src/DistributedStorage/run.php
        depends_on:
            - cassandra
